//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : smc.sm
//

#include "smc-fields.h"
#include "smc_sm.h"

using namespace statemap;

// Static class declarations.
SmcMap_Waiting SmcMap::Waiting("SmcMap::Waiting", 0);
SmcMap_Expect_Create SmcMap::Expect_Create("SmcMap::Expect_Create", 1);
SmcMap_Expect_Ident SmcMap::Expect_Ident("SmcMap::Expect_Ident", 2);
SmcMap_Waiting_Comma SmcMap::Waiting_Comma("SmcMap::Waiting_Comma", 3);
SmcMap_List_Expect_Ident SmcMap::List_Expect_Ident("SmcMap::List_Expect_Ident", 4);
SmcMap_Waiting_Closing_Brace_or_Comma SmcMap::Waiting_Closing_Brace_or_Comma("SmcMap::Waiting_Closing_Brace_or_Comma", 5);
SmcMap_List_Expect_After_Comma SmcMap::List_Expect_After_Comma("SmcMap::List_Expect_After_Comma", 6);
SmcMap_Ident_Finished SmcMap::Ident_Finished("SmcMap::Ident_Finished", 7);
SmcMap_Expect_As SmcMap::Expect_As("SmcMap::Expect_As", 8);
SmcMap_Expect_Join SmcMap::Expect_Join("SmcMap::Expect_Join", 9);
SmcMap_Done SmcMap::Done("SmcMap::Done", 10);
SmcMap_Exit_Fail SmcMap::Exit_Fail("SmcMap::Exit_Fail", 11);

void SmcFieldsState::curr_char(SmcClass& context, char c)
{
    Default(context);
}

void SmcFieldsState::eof(SmcClass& context)
{
    Default(context);
}

void SmcFieldsState::Default(SmcClass& context)
{
    throw (
        TransitionUndefinedException(
            (context.getState()).getName(),
            context.getTransition()));

}

void SmcMap_Waiting::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (isspace(c))
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::Waiting);
        context.getState().Entry(context);
    }
    else if (c == 'c')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.clearBuffer();
            ctxt.pushBuffer(c);
            ctxt.setRole(Init);
            context.setState(SmcMap::Expect_Create);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_Create);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_Waiting::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Expect_Create::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (ctxt.buffer == "create" && isspace(c))
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.clearBuffer();
            context.setState(SmcMap::Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.buffer.size() < 6)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushBuffer(c);
            context.setState(SmcMap::Expect_Create);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_Create);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_Expect_Create::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Expect_Ident::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (ctxt.buffer.empty() && isspace(c))
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::Expect_Ident);
        context.getState().Entry(context);
    }
    else if (ctxt.buffer.empty() && isalpha(c))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushBuffer(c);
            context.setState(SmcMap::Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && (isalnum(c) || c == '.' || c == '_'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushBuffer(c);
            context.setState(SmcMap::Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && (isspace(c) || c == '('))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setReconsume(true);
            context.setState(SmcMap::Ident_Finished);
        }
        catch (...)
        {
            context.setState(SmcMap::Ident_Finished);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_Expect_Ident::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Waiting_Comma::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (isspace(c))
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::Waiting_Comma);
        context.getState().Entry(context);
    }
    else if (c == ',')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushAttribute(ctxt.buffer);
            ctxt.clearBuffer();
            context.setState(SmcMap::List_Expect_After_Comma);
        }
        catch (...)
        {
            context.setState(SmcMap::List_Expect_After_Comma);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_Waiting_Comma::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_List_Expect_Ident::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (ctxt.buffer.empty() && isspace(c))
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::List_Expect_Ident);
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && isspace(c))

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::Waiting_Comma);
        context.getState().Entry(context);
    }
    else if (ctxt.buffer.empty() && isalpha(c))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushBuffer(c);
            context.setState(SmcMap::List_Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::List_Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && (isalnum(c) || c == '.' || c == '_'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushBuffer(c);
            context.setState(SmcMap::List_Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::List_Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && c == ',')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushAttribute(ctxt.buffer);
            ctxt.clearBuffer();
            context.setState(SmcMap::List_Expect_After_Comma);
        }
        catch (...)
        {
            context.setState(SmcMap::List_Expect_After_Comma);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && c == ')')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushAttribute(ctxt.buffer);
            ctxt.clearBuffer();
            context.setState(SmcMap::Done);
        }
        catch (...)
        {
            context.setState(SmcMap::Done);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_List_Expect_Ident::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Waiting_Closing_Brace_or_Comma::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (isspace(c))
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::Waiting_Closing_Brace_or_Comma);
        context.getState().Entry(context);
    }
    else if (c == ')')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushAttribute(ctxt.buffer);
            ctxt.clearBuffer();
            context.setState(SmcMap::Done);
        }
        catch (...)
        {
            context.setState(SmcMap::Done);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == ',')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushAttribute(ctxt.buffer);
            ctxt.clearBuffer();
            context.setState(SmcMap::List_Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::List_Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_Waiting_Closing_Brace_or_Comma::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_List_Expect_After_Comma::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (ctxt.buffer.empty() && isspace(c))
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::List_Expect_After_Comma);
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && isspace(c))

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::Waiting_Closing_Brace_or_Comma);
        context.getState().Entry(context);
    }
    else if (ctxt.buffer.empty() && isalpha(c))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushBuffer(c);
            context.setState(SmcMap::List_Expect_After_Comma);
        }
        catch (...)
        {
            context.setState(SmcMap::List_Expect_After_Comma);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && (isalnum(c) || c == '.' || c == '_'))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushBuffer(c);
            context.setState(SmcMap::List_Expect_After_Comma);
        }
        catch (...)
        {
            context.setState(SmcMap::List_Expect_After_Comma);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && c == ',')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushAttribute(ctxt.buffer);
            ctxt.clearBuffer();
            context.setState(SmcMap::List_Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::List_Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (!ctxt.buffer.empty() && c == ')')

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushAttribute(ctxt.buffer);
            ctxt.clearBuffer();
            context.setState(SmcMap::Done);
        }
        catch (...)
        {
            context.setState(SmcMap::Done);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_List_Expect_After_Comma::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Ident_Finished::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (isspace(c) && ctxt.role == Rhs)
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setJoinRhs(ctxt.buffer);
            context.setState(SmcMap::Done);
        }
        catch (...)
        {
            context.setState(SmcMap::Done);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (isspace(c))

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::Ident_Finished);
        context.getState().Entry(context);
    }
    else if (c == '(' && ctxt.role == Init)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setName(ctxt.buffer);
            ctxt.clearBuffer();
            ctxt.setRole(Att);
            ctxt.setType(Type::create);
            context.setState(SmcMap::List_Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::List_Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == ')' && ctxt.role == Att)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushAttribute(ctxt.buffer);
            ctxt.clearBuffer();
            context.setState(SmcMap::Done);
        }
        catch (...)
        {
            context.setState(SmcMap::Done);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == 'a' && ctxt.role == Init)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setName(ctxt.buffer);
            ctxt.setRole(Lhs);
            ctxt.setType(Type::join);
            ctxt.clearBuffer();
            ctxt.pushBuffer(c);
            context.setState(SmcMap::Expect_As);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_As);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == 'j' && ctxt.role == Lhs)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setJoinLhs(ctxt.buffer);
            ctxt.setRole(Rhs);
            ctxt.clearBuffer();
            ctxt.pushBuffer(c);
            context.setState(SmcMap::Expect_Join);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_Join);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_Ident_Finished::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Expect_As::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (ctxt.buffer == "as" && isspace(c))
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.clearBuffer();
            context.setState(SmcMap::Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.buffer.size() < 2)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushBuffer(c);
            context.setState(SmcMap::Expect_As);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_As);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_Expect_As::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Expect_Join::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (ctxt.buffer == "join" && isspace(c))
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.clearBuffer();
            context.setState(SmcMap::Expect_Ident);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_Ident);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (ctxt.buffer.size() < 4)

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.pushBuffer(c);
            context.setState(SmcMap::Expect_Join);
        }
        catch (...)
        {
            context.setState(SmcMap::Expect_Join);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(SmcMap::Exit_Fail);
        context.getState().Entry(context);
    }

}

void SmcMap_Expect_Join::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Done::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    if (isspace(c))
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(SmcMap::Done);
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setSuccess(false);
            context.setState(SmcMap::Waiting);
        }
        catch (...)
        {
            context.setState(SmcMap::Waiting);
            throw;
        }
        context.getState().Entry(context);
    }

}

void SmcMap_Done::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(true);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Exit_Fail::curr_char(SmcClass& context, char c)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

void SmcMap_Exit_Fail::eof(SmcClass& context)
{
    SmcFields& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.setSuccess(false);
        context.setState(SmcMap::Waiting);
    }
    catch (...)
    {
        context.setState(SmcMap::Waiting);
        throw;
    }
    context.getState().Entry(context);


}

//
// Local variables:
//  buffer-read-only: t
// End:
//
