//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : smc.sm
//

#ifndef SMC_SM_H
#define SMC_SM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class SmcMap;
class SmcMap_Waiting;
class SmcMap_Expect_Create;
class SmcMap_Expect_Ident;
class SmcMap_Waiting_Comma;
class SmcMap_List_Expect_Ident;
class SmcMap_Waiting_Closing_Brace_or_Comma;
class SmcMap_List_Expect_After_Comma;
class SmcMap_Ident_Finished;
class SmcMap_Expect_As;
class SmcMap_Expect_Join;
class SmcMap_Done;
class SmcMap_Exit_Fail;
class SmcMap_Default;
class SmcFieldsState;
class SmcClass;
class SmcFields;

class SmcFieldsState :
    public statemap::State
{
public:

    SmcFieldsState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(SmcClass&) {};
    virtual void Exit(SmcClass&) {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);

protected:

    virtual void Default(SmcClass& context);
};

class SmcMap
{
public:

    static SmcMap_Waiting Waiting;
    static SmcMap_Expect_Create Expect_Create;
    static SmcMap_Expect_Ident Expect_Ident;
    static SmcMap_Waiting_Comma Waiting_Comma;
    static SmcMap_List_Expect_Ident List_Expect_Ident;
    static SmcMap_Waiting_Closing_Brace_or_Comma Waiting_Closing_Brace_or_Comma;
    static SmcMap_List_Expect_After_Comma List_Expect_After_Comma;
    static SmcMap_Ident_Finished Ident_Finished;
    static SmcMap_Expect_As Expect_As;
    static SmcMap_Expect_Join Expect_Join;
    static SmcMap_Done Done;
    static SmcMap_Exit_Fail Exit_Fail;
};

class SmcMap_Default :
    public SmcFieldsState
{
public:

    SmcMap_Default(const char * const name, const int stateId)
    : SmcFieldsState(name, stateId)
    {};

};

class SmcMap_Waiting :
    public SmcMap_Default
{
public:
    SmcMap_Waiting(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_Expect_Create :
    public SmcMap_Default
{
public:
    SmcMap_Expect_Create(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_Expect_Ident :
    public SmcMap_Default
{
public:
    SmcMap_Expect_Ident(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_Waiting_Comma :
    public SmcMap_Default
{
public:
    SmcMap_Waiting_Comma(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_List_Expect_Ident :
    public SmcMap_Default
{
public:
    SmcMap_List_Expect_Ident(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_Waiting_Closing_Brace_or_Comma :
    public SmcMap_Default
{
public:
    SmcMap_Waiting_Closing_Brace_or_Comma(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_List_Expect_After_Comma :
    public SmcMap_Default
{
public:
    SmcMap_List_Expect_After_Comma(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_Ident_Finished :
    public SmcMap_Default
{
public:
    SmcMap_Ident_Finished(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_Expect_As :
    public SmcMap_Default
{
public:
    SmcMap_Expect_As(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_Expect_Join :
    public SmcMap_Default
{
public:
    SmcMap_Expect_Join(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_Done :
    public SmcMap_Default
{
public:
    SmcMap_Done(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcMap_Exit_Fail :
    public SmcMap_Default
{
public:
    SmcMap_Exit_Fail(const char * const name, const int stateId)
    : SmcMap_Default(name, stateId)
    {};

    virtual void curr_char(SmcClass& context, char c);
    virtual void eof(SmcClass& context);
};

class SmcClass :
    public statemap::FSMContext
{
public:

    explicit SmcClass(SmcFields& owner)
    : FSMContext(SmcMap::Waiting),
      _owner(owner)
    {};

    SmcClass(SmcFields& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline SmcFields& getOwner()
    {
        return (_owner);
    };

    inline SmcFieldsState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<SmcFieldsState&>(*_state);
    };

    inline void curr_char(char c)
    {
        getState().curr_char(*this, c);
    };

    inline void eof()
    {
        getState().eof(*this);
    };

private:
    SmcFields& _owner;
};


#endif // SMC_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
